### ISSUE TITLE
test_print_population is failing sometimes

### ISSUE THREAD

**Issue by njs59** [SABS-R3-Epidemiology/epiabm#165]
On one run we observed the failing test below:

FAIL: test_print_population (test_routine.test_file_population_config.TestPopConfig)
Tests method to print population to csv, to match content
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/sabsr3/Desktop/epiabm/pyEpiabm/pyEpiabm/tests/test_unit/test_routine/test_file_population_config.py", line 197, in test_print_population
    pd.testing.assert_frame_equal(mock_copy.call_args.args[0],
  File "/home/sabsr3/.local/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 1343, in assert_frame_equal
    assert_series_equal(
  File "/home/sabsr3/.local/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 1108, in assert_series_equal
    _testing.assert_almost_equal(
  File "pandas/_libs/testing.pyx", line 52, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 167, in pandas._libs.testing.assert_almost_equal
  File "/home/sabsr3/.local/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 679, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 4] (column name="household_number") are different

DataFrame.iloc[:, 4] (column name="household_number") values are different (50.0 %)
[index]: [0, 1]
[left]:  [2, 2]
[right]: [2, 3]

**Comment by njs59** [comment]
This error was very rare but it still needs fixing. You may need to run the unit tests lots of times before seeing this error.
